#!/usr/bin/env bash
# DevScope Plugin Setup
# Writes configuration to ~/.config/devscope/config
set -euo pipefail

CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/devscope"
CONFIG_FILE="$CONFIG_DIR/config"

echo "DevScope Plugin Setup"
echo "====================="
echo ""

# Server URL
read -rp "Server URL [http://localhost:6767]: " url
url="${url:-http://localhost:6767}"
# Strip trailing slash
url="${url%/}"

# API key
read -rp "API key (leave empty if none): " api_key

# Write config
mkdir -p "$CONFIG_DIR"
cat > "$CONFIG_FILE" <<EOF
# DevScope plugin configuration
# Generated by setup.sh
DEVSCOPE_URL="${url}"
DEVSCOPE_API_KEY="${api_key}"
EOF

chmod 600 "$CONFIG_FILE"

echo ""
echo "Config written to $CONFIG_FILE"
echo ""
echo "Testing connection..."
if curl -sf --max-time 5 "${url}/api/health" -o /dev/null 2>/dev/null; then
  echo "Connected to DevScope at ${url}"
else
  echo "Could not reach ${url}/api/health — server may not be running yet."
  echo "The plugin will retry on each event."
fi
