#!/usr/bin/env bash
# DevScope Plugin Setup
# Writes configuration to ~/.config/devscope/config
set -euo pipefail

CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/devscope"
CONFIG_FILE="$CONFIG_DIR/config"

echo "DevScope Plugin Setup"
echo "====================="
echo ""

# Server URL with validation
while true; do
  read -rp "Server URL [http://localhost:6767]: " url
  url="${url:-http://localhost:6767}"
  url="${url%/}"
  if echo "$url" | grep -qE '^https?://[a-zA-Z0-9._:/-]+$'; then
    break
  fi
  echo "Invalid URL. Must start with http:// or https://"
done

# API key with validation
while true; do
  read -rp "API key (leave empty if none): " api_key
  if [ -z "$api_key" ] || echo "$api_key" | grep -qE '^[a-zA-Z0-9_.:-]+$'; then
    break
  fi
  echo "Invalid API key. Only alphanumeric characters, dots, underscores, colons, and hyphens allowed."
done

# Privacy mode
echo ""
echo "Privacy mode controls what data is sent to the server."
echo "  private  — Only metadata (tool names, file paths, durations). No prompt text or command content."
echo "  standard — Adds prompt text and full tool inputs. (default)"
echo "  open     — Adds Claude's response content."
echo ""
read -rp "Privacy mode [standard]: " privacy
privacy="${privacy:-standard}"
case "$privacy" in
  private|standard|open) ;;
  *) privacy="standard" ;;
esac

# Write config
mkdir -p "$CONFIG_DIR"
cat > "$CONFIG_FILE" <<EOF
# DevScope plugin configuration
# Generated by setup.sh
DEVSCOPE_URL="${url}"
DEVSCOPE_API_KEY="${api_key}"
DEVSCOPE_PRIVACY="${privacy}"
EOF

chmod 600 "$CONFIG_FILE"

echo ""
echo "Config written to $CONFIG_FILE"
echo ""
echo "Testing connection..."
if curl -sf --max-time 5 "${url}/api/health" -o /dev/null 2>/dev/null; then
  echo "Connected to DevScope at ${url}"
else
  echo "Could not reach ${url}/api/health — server may not be running yet."
  echo "The plugin will retry on each event."
fi
